#Inventory Connector Range
#Range: 4 ~ 256
inventoryConnectorRange = 4
#Only Allow Trims to Connect Inventories
onlyTrimsConnect = false
#Inventory Cable Connector Maximum number of cables
#Range: > 16
invCableConnectorMaxScanSize = 16
#Wireless terminal reach
#Range: 4 ~ 64
wirelessReach = 4
#Wireless terminal reach
#Range: 16 ~ 512
advWirelessRange = 16
#Adv Wireless terminal requied beacon level for infinite range
#Value of 0 only requires a single beacon block nearby
#Value of -1 disables this feature entirely
#Range: -1 ~ 4
wirelessTermBeaconLvl = -1
#Adv Wireless terminal requied beacon level for cross dimensional access
#Value of 0 only requires a single beacon block nearby
#Value of -1 disables this feature entirely
#Range: -1 ~ 4
wirelessTermBeaconLvlDim = -1
#Inventory Cable Connector requied beacon level for inventory linking
#Value of 0 only requires a single beacon block
#Value of -1 disables this feature entirely
#Range: -1 ~ 4
invLinkBeaconLvl = -1
#Inventory Cable Connector requied beacon level for cross dimensional access
#Value of 0 only requires a single beacon block
#Value of -1 disables this feature entirely
#Range: -1 ~ 4
invLinkBeaconLvlDim = -1
#Inventory Connector duplicate finder max slot count
#Value of 0 only disables
#Range: > 0
invDupScanSize = 0

