
["Harder Spawners Control Values"]
	#Debug Level: 0 = Off, 1 = Log, 2 = Chat+Log
	#Range: 0 ~ 2
	debugLevel = 0
	#0 = chat messages on, 1 = chat messages off.
	#Range: 0 ~ 1
	spawnerTextOff = 1
	#Chance to destroy light sources in range (0-100%)
	#Range: 0 ~ 100
	destroyLightPercentage = 30
	#Range of light source destruction in blocks (1-7)
	#Range: 1 ~ 7
	destroyLightRange = 3
	#0- spawner breaks as normal.  Values over 0 minutes stun the spawner but don't break it.
	#Range: 0 ~ 27
	spawnerMinutesStunned = 0
	#Spawner Break Speed Modifier: 0 = Off, 1 = 50% slower, From 2 to 2.1 billion times slower
	#Range: > 0
	spawnerBreakSpeedMultiplier = 1
	#Spawner Revenge Level: 0 = Off, Over 1 spawner takes revenge on player.
	#Range: 0 ~ 11
	spawnerRevengeLevel = 1
	#Explode percentage when Spawners Break
	#Range: 0.0 ~ 100.0
	spawnersExplodePercentage = 5.0
	#Hostile Spawners: Player Range when hostile mobs start spawning
	#Range: 7 ~ 256
	requiredPlayerRange = 13
	#Hostile Spawners: Maximum Spawned Hostile Entities
	#Range: 3 ~ 256
	maxNearbyEntities = 5
	#Hostile Spawners: How far from spawner hostile mobs can spawn
	#Range: 4 ~ 256
	spawnRange = 7
	#hostileSpawnerLightLevel: Maximum Light Level for Hostile Spawners
	#Range: 0 ~ 15
	hostileSpawnerLightLevel = 11
	#hostileSpawnerResistDaylightDuration: give undead fire resistance (true) 
	#Range: 0 ~ 9999
	hostileSpawnerResistDaylightDuration = 120

["No Break Mobs Values 6464"]
	#Trail Block String 6464
	defaultNoBreakMobsActual = "harderspawners:default,0.2;minecraft:pig,0.0;minecraft:cow,0.0;minecraft:sheep,0.0;minecraft:parrot,0.0;minecraft:blaze,0.0;"

